import { Link } from '@tanstack/react-router';
import { Sparkles, Code, Zap, Eye, ChevronRight } from 'lucide-react';
import '../styles/landing.css';

export default function LandingPage() {
  return (
    <div className="landing">
      {/* Hero Section */}
      <section className="landing-hero">
        <nav className="landing-nav">
          <div className="landing-logo">
            <Sparkles className="h-6 w-6" />
            <span>Terranet</span>
          </div>
          <div className="landing-nav-links">
            <a href="#features">Features</a>
            <Link to="/auth">Sign In</Link>
            <Link to="/auth" className="landing-cta-button">
              Get Started
            </Link>
          </div>
        </nav>

        <div className="landing-hero-content">
          <h1 className="landing-hero-title">
            Generative Visual Intelligence
            <span className="landing-hero-subtitle">
              Create, visualize, and deploy interactive experiences with AI-powered code generation
            </span>
          </h1>
          <p className="landing-hero-description">
            Terranet transforms your ideas into living visualizations. From 3D scenes to interactive dashboards, 
            generate production-ready code through natural conversation.
          </p>
          <div className="landing-hero-ctas">
            <Link to="/auth" className="landing-cta-primary">
              Start Creating <ChevronRight className="h-4 w-4" />
            </Link>
            <a href="#demo" className="landing-cta-secondary">
              Watch Demo
            </a>
          </div>
        </div>

        {/* Hero Visual */}
        <div className="landing-hero-visual">
          <div className="landing-code-preview">
            <div className="landing-code-header">
              <div className="landing-code-dot red" />
              <div className="landing-code-dot yellow" />
              <div className="landing-code-dot green" />
              <span>scene.tsx</span>
            </div>
            <pre className="landing-code-body">
              <code>{`// Generated by Terranet
import { Canvas } from '@react-three/fiber';

export default function Scene() {
  return (
    <Canvas>
      <ambientLight intensity={0.5} />
      <pointLight position={[10, 10, 10]} />
      <mesh>
        <boxGeometry args={[1, 1, 1]} />
        <meshStandardMaterial color="orange" />
      </mesh>
    </Canvas>
  );
}`}</code>
            </pre>
          </div>
        </div>
      </section>

      {/* Features Section */}
      <section id="features" className="landing-features">
        <h2 className="landing-section-title">
          Visual Creation, <span>Reimagined</span>
        </h2>
        <p className="landing-section-subtitle">
          From concept to deployment in minutes, not hours
        </p>

        <div className="landing-features-grid">
          <FeatureCard
            icon={<Code className="h-6 w-6" />}
            title="AI-Powered Code Generation"
            description="Describe what you want to build. Terranet generates production-ready React, Three.js, and WebGL code automatically."
          />
          <FeatureCard
            icon={<Eye className="h-6 w-6" />}
            title="Real-time Preview"
            description="See your creations come to life instantly. Edit parameters and watch changes reflect in real-time."
          />
          <FeatureCard
            icon={<Zap className="h-6 w-6" />}
            title="Multi-skill Engine"
            description="From 3D visualizations to data dashboards, Terranet adapts to your creative needs with specialized AI agents."
          />
        </div>
      </section>

      {/* Showcase Section */}
      <section id="showcase" className="landing-showcase">
        <h2 className="landing-section-title">
          Create Without Limits
        </h2>
        
        <div className="landing-showcase-grid">
          <ShowcaseItem
            title="3D Visualizations"
            description="Interactive 3D scenes with React Three Fiber"
            preview="3d"
          />
          <ShowcaseItem
            title="Data Dashboards"
            description="Real-time data visualization components"
            preview="dashboard"
          />
          <ShowcaseItem
            title="Interactive UI"
            description="Animated interface components"
            preview="ui"
          />
          <ShowcaseItem
            title="Generative Art"
            description="Procedural graphics and shaders"
            preview="art"
          />
        </div>
      </section>

      {/* CTA Section */}
      <section className="landing-cta">
        <h2>Ready to Build?</h2>
        <p>Join thousands of creators using Terranet to bring their visions to life.</p>
        <Link to="/auth" className="landing-cta-primary">
          Get Started Free
        </Link>
      </section>

      {/* Footer */}
      <footer className="landing-footer">
        <div className="landing-footer-brand">
          <Sparkles className="h-5 w-5" />
          <span>Terranet</span>
        </div>
        <p className="landing-footer-copyright">
          © 2025 Terranet. Generative Visual Intelligence.
        </p>
      </footer>
    </div>
  );
}

function FeatureCard({ icon, title, description }: { icon: React.ReactNode; title: string; description: string }) {
  return (
    <div className="landing-feature-card">
      <div className="landing-feature-icon">{icon}</div>
      <h3>{title}</h3>
      <p>{description}</p>
    </div>
  );
}

function ShowcaseItem({ title, description, preview }: { title: string; description: string; preview: string }) {
  return (
    <div className="landing-showcase-item">
      <div className={`landing-showcase-preview landing-showcase-preview--${preview}`}>
        {/* Placeholder for actual preview */}
        <div className="landing-showcase-placeholder">
          <Sparkles className="h-8 w-8" />
        </div>
      </div>
      <h3>{title}</h3>
      <p>{description}</p>
    </div>
  );
}
